### ISSUE TITLE
Unable to start the backend process on windows machine

### ISSUE THREAD

**Issue by sofib** [shopgate/cloud-sdk#90]
After upgrading to platform-sdk@1.2.1 I'm no longer able to start backend process.
This is the output I'm getting:
```
$ sgconnect backend start
1/29/2018, 1:58:26 PM  INFO: Establishing SDK connection
1/29/2018, 1:58:27 PM  INFO: Selected application shop_31108
1/29/2018, 1:58:27 PM  INFO: Reset application
1/29/2018, 1:58:27 PM  INFO: Start syncing all local pipelines
1/29/2018, 1:58:27 PM  INFO: All pipelines are in sync now
1/29/2018, 1:58:27 PM  INFO: Runtime started
1/29/2018, 1:58:41 PM ERROR: websocket error
  Error: websocket error
      at WS.Transport.onError (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\engine.io-client\lib\transport.js:64:13)
      at WebSocket.ws.onerror (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\engine.io-client\lib\transports\websocket.js:150:10)
      at WebSocket.onError (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\ws\lib\EventTarget.js:109:16)
      at WebSocket.emit (events.js:159:13)
      at WebSocket.finalize (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\ws\lib\WebSocket.js:182:41)
      at TLSSocket.emit (events.js:159:13)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
The process thereafter hangs.

**Comment by pvomhoff** [comment]
The websocket ran into a timeout when you have bad connection.
We increased it to 10. The problem should be solved now.
