### ISSUE TITLE
Unable to start frontend after update to 1.2.2

### ISSUE THREAD

**Issue by sofib** [shopgate/cloud-sdk#91]
Output:
```
1/31/2018, 9:17:44 AM  INFO: Generating theme config
1/31/2018, 9:17:46 AM  INFO: Updated theme config
---------------------------------------------------------------------------
  S H O P G A T E   C L O U D
  D E V E L O P M E N T   S E R V E R
---------------------------------------------------------------------------
  RAPID available. Real data pipeline requests are possible ...
    STACK: https://rapid2-dev.shopgate.cloud
    SHOP:  31108
  RAPID connecting established!

  The development server is started. You can access the output by:

     http://10.0.76.133:8080

  Press CTRL-C to stop the server!
---------------------------------------------------------------------------
  Indexing widgets ...
  Indexing trackers ...

C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\@shopgate\cloud-sdk-webpack\lib\webpackConfig\helpers\indexes.js:46
  Object.keys(config).forEach(function (componentId) {
         ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at createIndex (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\@shopgate\cloud-sdk-webpack\lib\webpackConfig\helpers\indexes.js:46:10)
    at createPortalsIndex (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\@shopgate\cloud-sdk-webpack\lib\webpackConfig\helpers\indexes.js:108:21)
    at C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\@shopgate\cloud-sdk-webpack\lib\webpackDevServer\WebpackDevServer.js:66:41
    at Themes.init (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\@shopgate\cloud-sdk-webpack\lib\Themes.js:29:7)
    at WebpackDevServer.start (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\@shopgate\cloud-sdk-webpack\lib\webpackDevServer\WebpackDevServer.js:61:24)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\Shopgate\AppData\Roaming\npm\node_modules\@shopgate\platform-sdk\node_modules\@shopgate\cloud-sdk-webpack\index.js:10:62)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
```
The process thereafter hangs.
Additionally I'm unable to redeploy a shop.

**Comment by pvomhoff** [comment]
Its fixed with an update of the shop and sdk version 1.2.3
